[system]
arcade = false
playable = 3
menu_timer_seconds = 90

[window]
width = 1920
height = 1080
sizable = true
fullscreen = false
letterbox_color = "#000000"

[input]
latency_offset_seconds = 0.0

[card_reader]
mode = "pasori" # or mock

[card_reader.mock]
card_id = "00000000"

[api]
mode = "http"
endpoint = "https://api.xlair.dev"
timeout_seconds = 10.0

[api.mock]
data_directory = "data/mock/api"

[api.auth]
domain = ""
client_id = ""
client_secret = ""
audience = "https://api.xlair.dev"
