#pragma once

#define XLAIR_VERSION_MAJOR          0
#define XLAIR_VERSION_MINOR          0
#define XLAIR_VERSION_PATCH          0
#define XLAIR_VERSION_PRERELEASE_TAG U"indev"

#define XLAIR_MACRO_VAL(str)       #str
#define XLAIR_MACRO_TOSTRING(str)  XLAIR_MACRO_VAL(str)

#define XLAIR_VERSION                ((XLAIR_VERSION_MAJOR * 100 * 100) + (XLAIR_VERSION_MINOR * 100) + (XLAIR_VERSION_PATCH))
#define XLAIR_VERSION_SHORT_STRING   XLAIR_MACRO_TOSTRING(XLAIR_VERSION_MAJOR) U"." XLAIR_MACRO_TOSTRING(XLAIR_VERSION_MINOR) U"." XLAIR_MACRO_TOSTRING(XLAIR_VERSION_PATCH)
#define XLAIR_VERSION_STRING         XLAIR_VERSION_SHORT_STRING U" " XLAIR_VERSION_PRERELEASE_TAG
